version: '3.4'

services:
  albiberto:
    image: ${DOCKER_REGISTRY-}albibertoblazor
    build:
      context: .
      dockerfile: Albiberto.Blazor/Dockerfile
      
  loki:
    image: grafana/loki:latest
    
  promtail:
    image: grafana/promtail:latest
    
  grafana:
    image: grafana/grafana:latest