version: '3.4'

networks:
  loki:
  monitoring:
    driver: bridge
  infra:
    driver: bridge
    
volumes:
  postgres_data:
    name: ${POSTGRES_VOLUME}
      
  postgres-exporter_data: {}
  loki_data: {}
  grafana_data: {}
  node-exporter_data: {}
  prometheus_data: {}
    
services:
  
  albiberto:
    image: ${DOCKER_REGISTRY-}albiberto
    build:
      context: .
      dockerfile: Albiberto.Blazor/Dockerfile
    container_name: albiberto
    restart: unless-stopped
    networks:
      - loki
      - monitoring
      - infra
    
  postgres:
    image: postgres:${POSTGRES_TAG-latest}
    container_name: ${POSTGRES_CONTAINER_NAME-postgres}
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - monitoring
      - infra

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    restart: unless-stopped
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - loki
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring