version: '3.4'

networks:
  loki:
  monitoring:
    driver: bridge
  infra:
    driver: bridge
    
volumes:
  prometheus_data: {}
    
services:
  albiberto:
    image: ${DOCKER_REGISTRY-}albibertoblazor
    build:
      context: .
      dockerfile: Albiberto.Blazor/Dockerfile
    container_name: albiberto
    restart: unless-stopped
    networks:
      - loki
      - monitoring
      - infra
    
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    networks:
      - monitoring
      - infra
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    restart: unless-stopped
    networks:
      - monitoring
    
  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    networks:
      - loki
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    networks:
      - loki
      - monitoring
    
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks:
      - monitoring
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring