route:
  receiver: 'mail'
  repeat_interval: 5m
  group_by: [ alertname ]

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: ''
        auth_username: ''
        auth_password: ""
        from: ''
        to: ''